language: generic
sudo: required

services:
    - docker
    
before_install:
    - docker build -t rauradu/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true rauradu/docker-react npm run test
